### ISSUE TITLE
[Android] Does not work after ProGuard

### ISSUE THREAD

**Issue by nicoruti** [bennidi/mbassador#102]
I'm using the library in an Android project. It works fine, until I minify the app using ProGuard. There is no error or warning, the handler is just not notified anymore.

Here's my ProGuard-File content:

```
... skipped a lot of 'dontwarn' statements ...

-keepattributes Signature,InnerClasses,*Annotation*

# My event bus listener declaring @Handler statements
-keepclasseswithmembers class org.my.package.AndroidEventListener { *; }
-keepclasseswithmembers class javax.el.**,org.nustaq.**,javassist.**,net.engio.mbassy.**,org.objenesis.**,android.support.annotation.** { *; }
```

Do you have experience with mbassador on Android and an idea, what ProGuard removes, such that the event notification does not work anymore?

**Comment by bennidi** [comment]
Unfortunately I have no experiences with ProGuard whatsoever. I would expect the problem to be related to either reflection not being fully supported or annotations being removed.

**Comment by nicoruti** [comment]
I finally found the mistake... Use <code>keep</code> instead of <code>keepclasseswithmembers</code>. Here's the cleaned up version:

```
...
# For MBassador event bus
-keepattributes *Annotation*
-keep class javax.el.**,net.engio.**,android.support.annotation.** { *; }
-keep class org.my.package.AndroidEventListener { *; }
...
```
