### ISSUE TITLE
Error Handler Not Recognized

### ISSUE THREAD

**Issue by 3xp0n3nt** [bennidi/mbassador#106]
After upgrading to MBassador 1.2.1, I've simplified my event bus initialization code by using the default constructor, while still opting to add an error handler via the ```MBassador``` object itself, instead of in a ```BusConfiguration```:

```
final MBassador <Event> eventBus = new MBassador <> ();

eventBus.addErrorHandler (new IPublicationErrorHandler() {
  @Override
  public void handleError (final PublicationError error) {
    log.error (error.toString(), error.getCause());
  }
});
```
However, I now receive the following warning, which only began to occur in 1.2.1:

```
WARN: No error handler configured to handle exceptions during publication.
    Error handlers can be added to any instance of  AbstractPubSubSupport or via BusConfiguration.
    Falling back to console logger.
```

What's the point of allowing the the above method of adding an error handler in conjunction with a default constructor, if it doesn't recognize it? I hope it's just a simple bug...

I really don't want to have to do this, although it does eliminate the error message:

```
final MBassador <Event> eventBus = new MBassador <> (new BusConfiguration()
         .addFeature (Feature.SyncPubSub.Default())
         .addFeature (Feature.AsynchronousHandlerInvocation.Default())
         .addFeature (Feature.AsynchronousMessageDispatch.Default())
         .setProperty (Properties.Handler.PublicationError, new IPublicationErrorHandler() {
                @Override
                public void handleError (final PublicationError error) {
                  log.error (error.toString(), error.getCause());
                }
}));
```

P.S. Your warning log message has an extra space between the two words ```of  AbstractPubSubSupport```.

**Comment by 3xp0n3nt** [comment]
Ok, looking at the source, I see what's going on. ```AbstractPubSubSupport``` checks for a registered error handler in it's constructor, which occurs before I add an error handler, and it doesn't find one of course, so it triggers the warning message. I don't really agree with this design, as it forces one to use a BusConfiguration to register and error handler to avoid the error message, which forces one to not be able to use the simplified default constructor. Why not defer checking for an error handler until an actual message is published on the event bus?

**Comment by bennidi** [comment]
The reason for checking at construction time is that I don't want to check for it every time a message is published. I agree that it is a bit weird that the default constructor logs a warning to the console. But I think it's quite acceptable (I have seen that behaviour regularly in frameworks like Spring and others). I will maybe change the API there and move the error handler away from the actual PubSub interface and into the config. The error handler was introduced before the Runtime or Configuration classes evolved into their current position. You are very welcome to propose a change that makes this behaviour more consistent.

**Comment by davidsowerby** [comment]
I can see both sides of this discussion - the console message fooled me to begin with, but I can understand that something which is tuned for performance would avoid checking for the presence of a handler every time a message is sent.

@3xp0n3nt, however it is achieved, in order to have a parameterless constructor, there would need to be a default error handler ... there is no logger in AbstractPubSub (deliberately I guess) ...  so what would you suggest the default error handler behaviour should be - just write errors to the console?
 
BTW The text for the message was changed by #104

**Comment by 3xp0n3nt** [comment]
What about something like this:

```
public void handlePublicationError(PublicationError error) {
    if (errorHandlers.isEmpty()) {
        System.out.println("WARN: No error handler configured to handle exceptions during publication.\n" +
        "Publication error handlers can be added by AbstractPubSubSupport.addErrorHandler()\n" +
        "Configuration error handlers can be added by IBUsConfiguration.addConfigurationErrorHandler()\n" +
        "Falling back to console logger.");

        this.errorHandlers.add(new IPublicationErrorHandler.ConsoleLogger());
    }

    for (IPublicationErrorHandler errorHandler : errorHandlers) {
        errorHandler.handleError(error);
    }
}
```

**Comment by 3xp0n3nt** [comment]
@davidsowerby I'm fine with the default console logging of the default constructor. But if there is a method to add an error handler post-construction, and I choose to use that in conjunction with the default constructor, I don't want to see a spurious warning in the console.

**Comment by 3xp0n3nt** [comment]
Another idea would be to support this:

```
new MBassador <> (new IPublicationErrorHandler() {
        @Override
        public void handleError (PublicationError error) {
            log.error (error.toString(), error.getCause());
        }
      });
```

**Comment by davidsowerby** [comment]
I think I prefer your solution using 

     public void handlePublicationError(PublicationError error)

It seems to works quite well.  A console message would only appear when an error occurs, and there would be no impact on performance as the check is only made in response to an error.

Combining it with the suggestion from @bennidi to move the error handler away from the PubSub and into the configuration object would make a good change.

**Comment by davidsowerby** [comment]
@3xp0n3nt are you going to put in a PR for this?  If @bennidi is happy with the solution, I could provide a patch, but it may be a few days before I can get to it

**Comment by bennidi** [comment]
I think that the solution of moving PublicationErrorHandler away from the bus interface and entirely into the BusConfiguration is my preferred choice. This would still allow to do the configuration check at construction time and add the default logger to the bus if none is configured. The default setup of a valid BusConfiguration could be provided with a factory method and the default constructor of MBassador could use a configuration that has the error handler configured. A second constructor as proposed by @3xp0n3nt could just set the error handler accordingly. And yes, of course I'll take a PR on this one. A set of related unit tests would be very welcome :) Thanks!

**Comment by davidsowerby** [comment]
Ok, I'll try and get something done over the next week or so

**Comment by 3xp0n3nt** [comment]
@davidsowerby Thanks, I played around with the code, but didn't really want to put in the time to really think deeply through all of the design, and I wasn't completely happy with my modifications. So I'm glad you put something together.
