### ISSUE TITLE
handleError is invoked twice.

### ISSUE THREAD

**Issue by asaf** [bennidi/mbassador#118]
Hey,

It seems like `handleError` method of the `IPublicationErrorHandler interface is invoked twice when throwing an exception in the handler,

Is it an expected behavior or a bug? if it's by design, please explain why,

example:

```java
class ThrowExceptionWhenError implements IPublicationErrorHandler {
            @Override
            public void handleError(PublicationError error) {
               System.out.println("Invoked twice!!");
            }
        }

        MBassador bus = new MBassador(new BusConfiguration()
                .addFeature(Feature.SyncPubSub.Default())
                .addFeature(Feature.AsynchronousHandlerInvocation.Default())
                .addFeature(Feature.AsynchronousMessageDispatch.Default())
                .setProperty(Properties.Handler.PublicationError, new ThrowExceptionWhenError()));

      bus.publish(instanceOfSubMessage)
      .//some listener throw exception here...
```

Seems like `handlePublicationError` is invoked twice, one within `ReflectiveHandlerInvocation` due to `InvocationTargetException` caused by the handler that throws an exception as a part of the reflection method invocation, 

the second time is because MBsaddor:publication.execute() fails, it catches and invokes `handlePublicationError` again.

Thanks.

**Comment by bennidi** [comment]
Hey asaf,
I have added a test analogous to your code. I can not reproduce your described behaviour. I Assume in some way you add the error handler twice. The code of the `ReflectiveHandlerInvocation` clearly catches all exceptions and raises exactly one PublicationError.

If you take a look at `SyncBusTest.testExceptionInHandlerInvocation` you will see that there is already a test that ensures that the number of publication errors always equals the number of exceptions thrown. The test even checks concurrent scenarios.

I believe that there is an error somewhere in your code.
