### ISSUE TITLE
Need documentation for how to install error handler

### ISSUE THREAD

**Issue by basil-bourque** [bennidi/mbassador#120]
I cannot find any doc at all about installing an error handler. For each of my instantiated bus objects, I am getting the following message repeated in my logs:

    WARN: No error handler configured to handle exceptions during publication.
    Error handlers can be added to any instance of  AbstractPubSubSupport or via BusConfiguration. 
    Falling back to console logger.

The main product page:
https://github.com/bennidi/mbassador

…has this example code with a call to `addPublicationErrorHandler`:

    MBassador globalBus = new MBassador(new BusConfiguration()
         .addFeature(Feature.SyncPubSub.Default())
         .addFeature(Feature.AsynchronousHandlerInvocation.Default())
         .addFeature(Feature.AsynchronousMessageDispatch.Default())
         .addPublicationErrorHandler(new IPublicationErrorHandler{...})
         .setProperty(Properties.Common.Id, "global bus"));

Some discussion about that method and `IPublicationErrorHandler` would be helpful.

The method `addPublicationErrorHandler` is found in the source code for both [`IBusConfiguration`](https://github.com/bennidi/mbassador/blob/5bc924c11dd339fb288c69128d7d2faba58e3d07/src/main/java/net/engio/mbassy/bus/config/IBusConfiguration.java) and [`BusConfiguration`](https://github.com/bennidi/mbassador/blob/5bc924c11dd339fb288c69128d7d2faba58e3d07/src/main/java/net/engio/mbassy/bus/config/BusConfiguration.java), but not in either of their JavaDoc.

**Comment by bennidi** [comment]
Checkout the examples directory in the project root.
