### ISSUE TITLE
Handlers get message only the first time

### ISSUE THREAD

**Issue by fiunchinho** [bennidi/mbassador#128]
I'm trying to use mbassador in a Play based application that publish messages when certain routes are executed. When I start my application and visit the route that emits messages, handlers receive the message. But if I do it again, handlers won't get any message.

Looking through the documentation, I see this
> The basic contract of the bus is that it will deliver a specific message exactly once to each of the subscribed message handlers.

But the second time I visit the route, a new message is created with a different message UUID, so it should send the message to the handlers. Am I missing something here?

**Comment by nikoliazekter** [comment]
Could you please post [SSCCE](http://http://sscce.org/)?

**Comment by bennidi** [comment]
I assume you have weak references to your listeners. They have most likely
been GC'ed.

2015-11-08 12:19 GMT+01:00 Jose Armesto <notifications@github.com>:

**Comment by fiunchinho** [comment]
Ok, thanks
