### ISSUE TITLE
MBassador depends on ancient mycila-testing-mockito

### ISSUE THREAD

**Issue by HonggangLI** [bennidi/mbassador#133]
commit 6c19fd3bd9c7005c3f329fb43586db6ea7f45ad9
Author: David Sowerby <david.sowerby@virgin.net>
Date:   Mon Apr 13 14:18:20 2015 +0100

    PublicationErrorHandler moved to the BusConfiguration.  There are now 3 constructors for each bus type (MBassador and SyncMessageBus), enabling construction with either a) all default settings, b) all defaults plus a specified error handler or c) with a fully specified configuration.
    Unit tests added, build.gradle and pom.xml updated with assertj and mockito
------

This commit introduced dependency issue against ancient tool 'com.mycila.testing.plugins:mycila-testing-mockito:2.8'

http://mvnrepository.com/artifact/com.mycila.testing.plugins/mycila-testing-mockito/2.8

The homepage [1] of mycila is no longer active. So, the official old source code is unavailable. I'm importing a package into Fedora, which depends on MBassador.  Fedora requires all java libraries must be built/complied from source code. As mycila-testing-mockito code is unavailable, I can't build a rpm package for it. Then I can't build latest mbassador without modify. So, please remove or update this code to avoid ancient mycila-testing-mockito. Thanks

[1] http://old.mycila.com/p/mycila/mycila-testing/plugins/mycila-testing-mockito/

**Comment by bennidi** [comment]
@HonggangLI Thanks for reporting. I will review the PR and make a release within the next 5-7 days.
@davidsowerby Thanks for responding so quickly. Great first level support :+1:

**Comment by HonggangLI** [comment]
@davidsowerby Thank you!
@bennidi Please make a release, then I can open a package Review Request to import MBassador into Fedora. And build our package against MBassador. Thanks
