### ISSUE TITLE
Failed to build mbassador with maven offline mode for Fedora

### ISSUE THREAD

**Issue by HonggangLI** [bennidi/mbassador#135]
==================
commit 005915b42e2486f5095893a4429db32fcc5341ec
Author: bennidi <b.diedrichsen@gmail.com>
Date:   Fri Jun 19 16:32:30 2015 +0200

    fixed pmd codestyle errors
==================

This commit introduced dependency against nazgul-codestyle-4.1.1. Unfortunately. rpm package for nazgul-codestyle is unavailable. That means we can't build mbassadaor with maven offline mode enabled. After revert the pom.xml changes introduced by the commit, building works again.

==============
cat nazgul_codestyle_issue.patch 
diff --git a/pom.xml b/pom.xml
index 4b9abff..c2f57ad 100644
--- a/pom.xml
+++ b/pom.xml
@@ -53,7 +53,6 @@
         <nazgul-codestyle.version>2.0.1</nazgul-codestyle.version>
         <jdk.version>1.6</jdk.version>
         <pmd.plugin.version>3.0.1</pmd.plugin.version>
-        <nazgul.codestyle.version>4.1.1</nazgul.codestyle.version>
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         <project.build.java.version>1.6</project.build.java.version>
         <github.url>file://${project.basedir}/mvn-local-repo</github.url>
@@ -131,7 +130,7 @@
 
     <build>
         <plugins>
-            <plugin>
+            
 
             <plugin>
                 <groupId>org.apache.felix</groupId>
================

Please fix this issue, thanks.

**Comment by bennidi** [comment]
Fixed in 1.4.2.2

**Comment by HonggangLI** [comment]
"Fixed in 1.4.2.2"
               ^^^^^^

Is it a typo? And could you please provide the commit ID which fixes this issue?

**Comment by HonggangLI** [comment]
1.4.2.2? Is it a typo?

**Comment by bennidi** [comment]
Yes. 1.2.4.2
Sorry
