### ISSUE TITLE
org.fedoraproject.xmvn.tools.install.ArtifactInstallationException: Installation repository is incapable of holding artifact org.mbassy:mbassador-mbassador-1.2.4.2:war:SYSTEM

### ISSUE THREAD

**Issue by HonggangLI** [bennidi/mbassador#137]
Start: rpmbuild mbassador-1.2.4.2-1.fc25.src.rpm
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.EzF5Gj
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf mbassador-mbassador-1.2.4.2
+ /usr/bin/gzip -dc /builddir/build/SOURCES/mbassador-1.2.4.2.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd mbassador-mbassador-1.2.4.2
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.5Errd0
+ umask 022
+ cd /builddir/build/BUILD
+ cd mbassador-mbassador-1.2.4.2
+ /usr/bin/python3 /usr/share/java-utils/mvn_build.py --gradle
Executing: gradle-local --no-daemon --offline build xmvnInstall
['gradle-local', '--no-daemon', '--offline', 'build', 'xmvnInstall']
:compileJava
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:jar:SYSTEM as it has duplicate metadata
Ignoring metadata for artifact pmd:pmd:pom:SYSTEM as it has duplicate metadata
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources UP-TO-DATE
:classes
:war
:assemble
:compileTestJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:processTestResources
:testClasses
:test
:check
:build
:xmvnInstall

BUILD SUCCESSFUL

Total time: 1 mins 4.606 secs
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.UUgYGz
+ umask 022
+ cd /builddir/build/BUILD
+ '[' /builddir/build/BUILDROOT/mbassador-1.2.4.2-1.fc25.x86_64 '!=' / ']'
+ rm -rf /builddir/build/BUILDROOT/mbassador-1.2.4.2-1.fc25.x86_64
++ dirname /builddir/build/BUILDROOT/mbassador-1.2.4.2-1.fc25.x86_64
+ mkdir -p /builddir/build/BUILDROOT
+ mkdir /builddir/build/BUILDROOT/mbassador-1.2.4.2-1.fc25.x86_64
+ cd mbassador-mbassador-1.2.4.2
+ xmvn-install -R .xmvn-reactor -n mbassador -d /builddir/build/BUILDROOT/mbassador-1.2.4.2-1.fc25.x86_64
[INFO] Installing artifact org.mbassy:mbassador-mbassador-1.2.4.2:war:1.2.4-SNAPSHOT
[ERROR] Artifact installation failed
org.fedoraproject.xmvn.tools.install.ArtifactInstallationException: Installation repository is incapable of holding artifact org.mbassy:mbassador-mbassador-1.2.4.2:war:SYSTEM
	at org.fedoraproject.xmvn.tools.install.impl.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:117)
	at org.fedoraproject.xmvn.tools.install.impl.DefaultInstaller.installArtifact(DefaultInstaller.java:218)
	at org.fedoraproject.xmvn.tools.install.impl.DefaultInstaller.install(DefaultInstaller.java:330)
	at org.fedoraproject.xmvn.tools.install.cli.InstallerCli.run(InstallerCli.java:65)
	at org.fedoraproject.xmvn.tools.install.cli.InstallerCli.main(InstallerCli.java:86)
error: Bad exit status from /var/tmp/rpm-tmp.UUgYGz (%install)
    Bad exit status from /var/tmp/rpm-tmp.UUgYGz (%install)

RPM build errors:
ERROR: Exception(src/mbassador-1.2.4.2-1.fc25.src.rpm) Config(fedora-rawhide-x86_64) 3 minutes 55 seconds
INFO: Results and/or logs in: noarch
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
Finish: clean chroot
ERROR: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/mbassador.spec

**Comment by bennidi** [comment]
What do the logs say?

**Comment by HonggangLI** [comment]
The log is rpmbuild log for Fedora Rawhind (Fedora 25). Failed to install mbassador with "%mvn_istall" macro after built it with "%gradle_build" macro.

[mbassador.spec.txt](https://github.com/bennidi/mbassador/files/191277/mbassador.spec.txt)
[mock.log.txt](https://github.com/bennidi/mbassador/files/191278/mock.log.txt)
