### ISSUE TITLE
Handlers in inner classes not recognized

### ISSUE THREAD

**Issue by fgrazi** [bennidi/mbassador#147]
I noticed that methods of inner classes annotated with @Handler are not recognized, For example:

    public class MyClass {
        @Handler
        public void handle(Notification notification) {
            System.out.println(notification); // this works
        }

        public static class MyInnerClass {

            @Handler
            public void handle(Notification notification) {
                System.out.println(notification); // does not work
            }
        }

    }

Is it possible to extend recognition of listeners to inner classes?

**Comment by chriskingnet** [comment]
Hello @fgrazi, 

I was going to pick this up to work on, however this actually seems to me to be expected behaviour. If I want to subscribe the MyInnerClass listener, I should subscribe it explicitly. What do you think?

**Comment by fgrazi** [comment]
Hi Chris, yes you are absolutely right. I'm sure that when I opened the issue I subscribed it explicitly and did not work. Maybe I was using an old version. I tried again right now on a small chunk of code and it works fine. Maybe I was goofing at something else. Please consider the issue closed and congratulations! Mbassador is really useful. I migrated to it from Guice EventBus and use effectively in Vaadin applications. Cheers, Franco.
