### ISSUE TITLE
Create a project with the interfaces/annotations

### ISSUE THREAD

**Issue by LukMas** [bennidi/mbassador#158]
Hi! 

I would like to have a project where all the main interfaces/annotations are collected and separated from their implementation. In this way I can create a project that depends just upon the basic interfaces/annotations, without having to deal with the whole mbassador project.

**Comment by bennidi** [comment]
Have a look at #153

**Comment by LukMas** [comment]
Thanks, I've read it. 
Anyway, I think that my question is a bit different.
I explain it better. 

I have a library, **ContextALibrary**, that has just some dependencies. In this project I've a *ProcessManagerClass* that uses my *SystemEventBus* interface to work. 

The SystemEventBus is a custom interface that is defined in another library, **EventBusLibrary**. 
I've done this because, I like to split interfaces from their implementation (so if one day my boss says "We have to use another EventBus because we have this request!" only the implementation of the SystemEventBus changes). 

Its implementation with MBassador is in **EventBusMBassadorLibrary**. 

Actually, to make the things working in the ContextALibrary I've had to add the annotations to the ProcessManagerClass, bringing in a way or another the MBassador as dependency. At first sight it is nothing so bad. But now: 
- Option 1: ContextALibrary has  a direct dependency to EventBusMBassadorLibrary, so whenever I change MBassador in EventBusMBassadorLibrary an update in ContextALibrary is done too
  - I've lost my separation between my interface and my implementation that uses MBassador
  - A change in one library could generate a waterfall of changes in several libraries
  - (I have classes that are useless in my library because I work just with the interfaces)
- Option 2: ContextALibrary has  a dependency to MBassador, so no update is done in ContextALibrary if I change EventBusMBassadorLibrary
  - this options looks better, but every time I add both the libraries (ContextALibrary and EventBusMBassadorLibrary) I've to remember to exclude MBassador from one (hopefully ContextALibrary)

At the end, all comes from this book: https://www.amazon.com/dp/0321204654
It's suggested to split the interfaces from their implementations (and also the annotation, I would say). In this way you obtain a great separation between the different layers of the software.

**Comment by LukMas** [comment]
The project I work it's big enough (and it needs a long refactoring step)
that applying any patter before gives just a bit of help to don't improve
its "entropy".
Anyway, my request was far more a "I would like" then a real problem. I
understand that you're really busy and that doing this is far away from
your priorities. So don't say sorry; it's already a lot the fact that you
offer us, for free, such a great piece of software.

Thank you for your time.
