### ISSUE TITLE
Messages pooling

### ISSUE THREAD

**Issue by Namek** [bennidi/mbassador#54]
Hi!
Is it possible to pool created messages? I mean, that I can simply obtain new messages/events from my own pool, but I can't find a proper moment to free those objects (put them back into the pool).

**Comment by chirhotec** [comment]
@Namek did you ever find a good eventbus for libGDX that GWT compatible?

**Comment by Namek** [comment]
@chirhotec 
https://github.com/DaanVanYperen/artemis-odb-contrib/tree/master/contrib-eventbus/src/main/java/net/mostlyoriginal
https://github.com/DaanVanYperen/artemis-odb-contrib/wiki/EventBasics
