### ISSUE TITLE
Limitations of handler priority

### ISSUE THREAD

**Issue by arne-vandamme** [bennidi/mbassador#76]
I have a question related to priorities of handlers.  Let me draw my use case (trying to be detailed enough):

**Problem description**
We have an application consisting of several functional modules.  These modules can depend on each other.  

Example:
- module C depends on B, module B depends on module A

In this case:
- module C can use services from B and A, not the other way around
- module A is bootstrapped first (ApplicationContext created, database configured etc), then B, then C

In short: all modules have a reliable order relative to the modules they depend on.
MBassador is used as the event bus for the entire application, and a way for modules to define extension points.  What I want to achieve is that events are handled first by module A, then B and then C.

Using the current priority value is impossible as the actual order is only determined upon application start when the dependencies are calculated.   

Even though in an ideal situation message handlers should not depend on each other, i still want to have reliable default behavior following the logic of the module hierarchy as this will benefit us in all but the exceptional cases.  In fact I find this much more logical than a single module fixing a handler on for example priority 10, because there is no way to determine what 10 means in a specific application setup, and no way to know what other modules use the same priority.

**Possible solutions i see:**
_1. Define an mbassador bus hierarchy in the application, where every module has its own and a central bus dispatches in order to the modules_
I do not really like this approach as it poses overhead (an application can have tons of modules) and would make it hard for handlers to explicitly jump in front of handlers from other modules.

_2. Allow MBassador listener priority to be defined when subscribing_
If there is a listener priority but no handler priority - that one is used.  If there is a handler priority specified it takes precedence.  This would go a long way, and be very easy to use for new MBassador users; but i think it has less flexibility than option 3.

_3. Have an ability to "calculate" the runtime priority for a handler_
Some form of callback mechanism with both handler metadata and listener instance  (not class) would probably offer most flexibility.  Perhaps more work to implement from an application point of view, but it could offer multi level priorities.  It would allow me to use annotations to define handler priority within modules, but use the module priority as the first level.

Option 1 probably can be done with the current MBassador functionality, but I do think the priority value right now is very limiting.  I do think it should be possible for 2 different instances of the same listener class to have their own priority because they can be parameterized differently.

However I noticed that to implement something like 3, it would mean some architectural changes to the Subscription setup (as we need to switch to handler/listener priority instead of handlermetadata)... so I'd like to hear some thoughts or suggestions on this first.

**Comment by bennidi** [comment]
Doesn't seem to get a lot of attention from other users. Closing for now...
