### ISSUE TITLE
Need best practices example of construction.

### ISSUE THREAD

**Issue by garretwilson** [bennidi/mbassador#94]
Unfortunately both examples of constructing `MBassador` in the [documentation](https://github.com/bennidi/mbassador) are incorrect. The instructions say to use `new MBassador(BusConfiguration.SyncAsync())`, which has been deprecated (at least in version 1.2.0). And the code has `new MBassador<TestMessage>()`, which doesn't even work --- there doesn't appear to be a default constructor for `MBassador`. The `BusConfiguration` documentation says to "Use feature driven configuration instead". But what does that mean? What are best practices? What should I do by default?

Supposedly `MBassador` is very simple to get up and running. The documentation should at least show correctly how to do that. Thanks.

**Comment by 3xp0n3nt** [comment]
I don't know if it's "best practices", but here's what I currently do:

```
final IBusConfiguration eventBusConfiguration = new BusConfiguration()
        .addFeature (Feature.SyncPubSub.Default())
        .addFeature (Feature.AsynchronousHandlerInvocation.Default())
        .addFeature (Feature.AsynchronousMessageDispatch.Default());

final MBassador <Event> eventBus = new MBassador <> (eventBusConfiguration);

eventBus.addErrorHandler (new IPublicationErrorHandler() {
  @Override
  public void handleError (final PublicationError error) {
    log.error (error.toString(), error.getCause());
  }
});

```

**Comment by bennidi** [comment]
@garretwilson Which version are you using? Mbassador has a default constructor. Simply use `MBassador bus = new MBassador ();` to create an instance. The construction that @3xp0n3nt  suggests is actually the code used in the default constructor. I will update the documentation soon. Maybe you could spend some more time looking into source code - this really helps when working with OSS. Since nobody pays you to do anything, it is not always expectable to find enterprise quality documentation.

**Comment by 3xp0n3nt** [comment]
@bennidi I'm using 1.2.0 and see no such constructor. I can see it in the GitHub source though.

**Comment by bennidi** [comment]
Really? In that case please excuse my smart-ass attitude. I assumed that my code was actually identical to 1.2.0. I need to make another release then. Until then you will have to use the method suggested by @3xp0n3nt

**Comment by enwired** [comment]
The suggested code by @3xp0n3nt includes an error handler, which is a very good idea.  We initially did not add an error handler, so errors simply went unreported and were quite hard to track down.

Even if one sets a default exception handler with Thread.setDefaultUncaughtExceptionHandler(), exceptions in message handling will simply disappear unless an IPublicationErrorHandler is added to the bus.

**Comment by bennidi** [comment]
This behaviour has changed in 1.2.1. The configuration validation routine will log a warning to the console when no `IPublicationErrorHandler` is configured and will add a console logger such that exceptions are logged to sysout.

**Comment by enwired** [comment]
Yes, I just noticed that 1.2.1 has been released.  Thanks.
Is there a way to set up a bus which only allows synchronous publishing, and not asynchronous publishing?

If I use a configuration with no asynch configuration, it will give an exception.

```java
    IBusConfiguration eventBusConfiguration = new BusConfiguration()
        .addFeature (Feature.SyncPubSub.Default());
    bus = new MBassador<Object>(eventBusConfiguration);
```

**Comment by bennidi** [comment]
You need to use the SyncXXBus. Check the Javadocs for more details.
