### ISSUE TITLE
No-arg constructor not allowed, contrary to example in documentation.

### ISSUE THREAD

**Issue by basil-bourque** [bennidi/mbassador#98]
The [README.md](https://github.com/bennidi/mbassador) shows an example with this no-argument constructor in mbassador 1.2.0:

    MBassador<TestMessage> bus = new MBassador<TestMessage>();

An error appears in NetBeans 8.0.2 saying "constructor could not be applied", that an [`IBusConfiguration`](http://bennidi.github.io/mbassador/net/engio/mbassy/bus/config/IBusConfiguration.html).

I could only get the following to work for instantiating the event bus where `DataEvent` is my own class (of course).

Member variable:

    MBassador<DataEvent> eventBus;

Initializing code:

    BusConfiguration busConfig = new BusConfiguration();
    busConfig.addFeature( Feature.SyncPubSub.Default() );
    busConfig.addFeature( Feature.AsynchronousHandlerInvocation.Default() );
    busConfig.addFeature( Feature.AsynchronousMessageDispatch.Default() );
    this.eventBus = new MBassador<>( busConfig );

**Comment by 3xp0n3nt** [comment]
You're correct. See #94.
